[package]
name = "qoeurcp_timer"
version = "0.0.0"
authors = ["monsieurbadia <iam@monsieurbadia.com>"]
edition = "2018"

description = """
the timer for the qoeur compiler programming
"""

[lib]
name = "qoeurcp_timer"
path = "src/lib.rs"
doctest = false

[dependencies]
time = "0.1.30"
