[package]
name = "qoeurcp_session"
version = "0.0.0"
authors = ["monsieurbadia <iam@monsieurbadia.com>"]
edition = "2018"

description = """
the session for the qoeur compiler programming
"""

[lib]
name = "qoeurcp_session"
path = "src/lib.rs"
doctest = false

[dependencies]
toml = "0.5.8"
